# Backend configuration: Connects to your GitHub repository
backend:
  name: github
  repo: domanhthang2110/wsvnwiki # <<< YOUR_USERNAME/YOUR_REPO_NAME
  branch: main # Or your default branch name
  auth_type: implicit # Easiest auth for local testing

# Enables a workflow where you can save drafts, mark for review, and then publish.
publish_mode: editorial_workflow

# Media configuration: Where images uploaded via the CMS will be stored
media_folder: "public/images/uploads" # Path in your Git repo
public_folder: "/images/uploads" # Public URL path for the website

# Collections: Defines all the different types of content you can manage.
collections:
  # 1. Simple Site-wide Settings
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "content/settings.yml"
        label: "General Settings"
        name: "general"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Site Description", name: "description", widget: "text" }

  # 2. Game Classes (UPDATED with Skills relation)
  - name: "classes"
    label: "Classes"
    label_singular: "Class"
    folder: "content/classes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Class Name", name: "title", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image", optional: true }
      - { label: "Description", name: "body", widget: "markdown" }
      - label: "Skills" # <<< ADDED THIS FIELD
        name: "skills"
        widget: "relation"
        collection: "skills" # Links to the 'skills' collection
        search_fields: ["title"]
        value_field: "{{slug}}" # Store a list of skill slugs
        display_fields: ["title"]
        multiple: true # Allows selecting MULTIPLE skills
        optional: true

  # 3. Game Skills (SIMPLIFIED - No Class relation)
  - name: "skills"
    label: "Skills"
    label_singular: "Skill"
    folder: "content/skills"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Skill Name", name: "title", widget: "string" }
      - { label: "Icon", name: "icon", widget: "image", optional: true }
      - { label: "Skill Tier", name: "skill_tier", widget: "select", options: ["Basic", "Expert"] }
      - { label: "Activation Type", name: "activation_type", widget: "select", options: ["Active", "Passive"] }
      # --- Associated Class field is REMOVED ---
      - label: "Description Template"
        name: "description_template"
        widget: "text"
        hint: "Use placeholders like {damage}, {duration}."
      - label: "Level Data"
        name: "levels"
        widget: "list"
        fields:
          - { label: "Level Number", name: "level_number", widget: "number", value_type: "int" }
          - label: "Skill Parameters"
            name: "parameters"
            widget: "list"
            summary: "{{fields.key}}: {{fields.value}}"
            fields:
              - { label: "Parameter Key (e.g., damage, cooldown)", name: "key", widget: "string", hint: "MUST match a placeholder." }
              - { label: "Value", name: "value", widget: "string" }
      - { label: "Detailed Notes (Optional)", name: "body", widget: "markdown", optional: true }

  # 4. Tags (For Guides/Others)
  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    folder: "content/tags"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tag Name", name: "title", widget: "string" }

  # 5. Guides
  - name: "guides"
    label: "Guides"
    label_singular: "Guide"
    folder: "content/guides"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "featured_image", widget: "image", optional: true }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "relation", collection: "tags", search_fields: ["title"], value_field: "title", multiple: true, optional: true }

  # 6. Others (Similar to Guides)
  - name: "others"
    label: "Others"
    label_singular: "Other Post"
    folder: "content/others"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "featured__image", widget: "image", optional: true }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "relation", collection: "tags", search_fields: ["title",], value_field: "title", multiple: true, optional: true }