name: Sync Events (Cron)

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:    # Allow manual run

jobs:
  sync-events:
    runs-on: ubuntu-latest

    steps:
      - name: Call sync-events API
        run: |
          curl -X GET "https://wsvnwiki.vercel.app/api/cron/sync-events" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
